# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>

name: Feature request
description: Suggest a change to an existing package
labels: ["enhancement"]
body:
  - type: input
    id: package
    attributes:
      label: Package
      placeholder: gpd-pocket-config
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What does the package not do today that it should?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What you would like it to do
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
      description: Including doing it outside the package entirely.
