#!/usr/bin/env python3

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>

"""Reconcile ``pkgrel`` and ``.SRCINFO`` after multicz writes ``pkgver``.

Run as a multicz ``post_bump`` hook, once per component::

    post_bump = ["python3 scripts/pkgbuild-sync.py packages/gpd-pocket-config"]

By the time the hook fires, multicz has already written the new version
into ``PKGBUILD``'s ``pkgver=`` line. Two things then have to follow, and
neither is something multicz can know about:

``pkgrel``
    Arch resets it to ``1`` on every upstream version change; it only
    advances when the *same* sources are rebuilt. The old value is read
    back from ``.SRCINFO`` (the last released state), so the rule is
    exact rather than guessed: ``pkgver`` moved -> ``pkgrel=1``;
    ``pkgver`` unchanged -> leave ``pkgrel`` alone, which is the plain
    rebuild case.

    A package whose ``pkgver`` tracks upstream never reaches this hook:
    it declares no ``bump_files`` at all. multicz cannot own ``pkgrel``
    either - pacman requires a positive integer, and a semantic version
    is not one.

``.SRCINFO``
    Consumed by the AUR to populate the web interface and the dependency
    solver, and it must agree with the ``PKGBUILD`` byte for byte. The
    authoritative generator is ``makepkg --printsrcinfo``, which only
    runs on Arch - the release job runs on ``ubuntu-latest``. A release
    changes exactly two fields, so this rewrites those two lines in place
    and leaves the rest of the generated file untouched. Anything
    structural (a new ``depends``, a new ``source``) is regenerated by
    the author with ``scripts/srcinfo.sh`` and verified in CI by the
    ``srcinfo`` job, which runs real ``makepkg`` in an Arch container and
    fails on any drift.

Exits non-zero on anything it cannot prove, so a broken hook fails the
release rather than pushing an inconsistent package to the AUR.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# ``pkgver=1.2.3`` / ``pkgrel=1`` at the start of a line. PKGBUILDs are
# bash, so the value may be quoted; both forms are accepted and the
# original quoting style is preserved on rewrite.
_PKGBUILD_FIELD = (
    r"^(?P<prefix>{field}=)(?P<quote>[\"']?)(?P<value>[^\"'\s#]*)(?P=quote)"
)
# ``\tpkgver = 1.2.3`` in the generated .SRCINFO. Indentation is a tab.
_SRCINFO_FIELD = r"^(?P<prefix>\s*{field} = )(?P<value>.*)$"


def _read_pkgbuild_field(text: str, field: str) -> str:
    match = re.search(_PKGBUILD_FIELD.format(field=field), text, re.MULTILINE)
    if match is None:
        raise SystemExit(f"pkgbuild-sync: no {field}= assignment found in PKGBUILD")
    return match.group("value")


def _write_pkgbuild_field(text: str, field: str, value: str) -> str:
    pattern = re.compile(_PKGBUILD_FIELD.format(field=field), re.MULTILINE)
    new, count = pattern.subn(
        lambda m: f"{m.group('prefix')}{m.group('quote')}{value}{m.group('quote')}",
        text,
        count=1,
    )
    if count != 1:
        raise SystemExit(f"pkgbuild-sync: could not rewrite {field}= in PKGBUILD")
    return new


def _read_srcinfo_field(text: str, field: str) -> str | None:
    match = re.search(_SRCINFO_FIELD.format(field=field), text, re.MULTILINE)
    return None if match is None else match.group("value").strip()


def _write_srcinfo_field(text: str, field: str, value: str) -> str:
    pattern = re.compile(_SRCINFO_FIELD.format(field=field), re.MULTILINE)
    new, count = pattern.subn(lambda m: f"{m.group('prefix')}{value}", text, count=1)
    if count != 1:
        raise SystemExit(f"pkgbuild-sync: could not rewrite '{field} = ' in .SRCINFO")
    return new


def sync(package_dir: Path) -> int:
    pkgbuild = package_dir / "PKGBUILD"
    srcinfo = package_dir / ".SRCINFO"
    for path in (pkgbuild, srcinfo):
        if not path.is_file():
            raise SystemExit(f"pkgbuild-sync: missing {path}")

    pkgbuild_text = pkgbuild.read_text(encoding="utf-8")
    srcinfo_text = srcinfo.read_text(encoding="utf-8")

    new_pkgver = _read_pkgbuild_field(pkgbuild_text, "pkgver")
    # The .SRCINFO still holds the previously released state: multicz has
    # rewritten the PKGBUILD but nothing has touched this file yet.
    old_pkgver = _read_srcinfo_field(srcinfo_text, "pkgver")

    if old_pkgver is not None and old_pkgver != new_pkgver:
        pkgbuild_text = _write_pkgbuild_field(pkgbuild_text, "pkgrel", "1")
        reset = True
    else:
        reset = False

    pkgrel = _read_pkgbuild_field(pkgbuild_text, "pkgrel")

    srcinfo_text = _write_srcinfo_field(srcinfo_text, "pkgver", new_pkgver)
    srcinfo_text = _write_srcinfo_field(srcinfo_text, "pkgrel", pkgrel)

    pkgbuild.write_text(pkgbuild_text, encoding="utf-8")
    srcinfo.write_text(srcinfo_text, encoding="utf-8")

    print(
        f"pkgbuild-sync: {package_dir.name} "
        f"pkgver {old_pkgver} -> {new_pkgver}, pkgrel={pkgrel}"
        f"{' (reset)' if reset else ''}"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "package_dir",
        type=Path,
        help="path to packages/<name>, holding the PKGBUILD and .SRCINFO",
    )
    args = parser.parse_args(argv)
    return sync(args.package_dir)


if __name__ == "__main__":
    sys.exit(main())
